adb shell pm uninstall -k --user 0 flipboard.app
adb shell pm uninstall -k --user 0 com.google.android.apps.books
adb shell pm uninstall -k --user 0 com.google.android.apps.plus
adb shell pm uninstall -k --user 0 com.google.android.apps.music
adb shell pm uninstall -k --user 0 com.google.android.play.games
adb shell pm uninstall -k --user 0 com.google.android.apps.magazines
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.n7mobile.asterix.tmobilemuzyka
adb shell pm uninstall -k --user 0 pl.k2.droidoaudioteka.pl.tmobile
adb shell pm uninstall -k --user 0 pl.tmobile.panel
adb shell pm uninstall -k --user 0 pl.tmobile.miboa
adb shell pm uninstall -k --user 0 com.ptc.osp.gnc
adb shell pm uninstall -k --user 0 com.naviexpert.NaviExpert
adb shell pm uninstall -k --user 0 com.exent.android.gametanium.tmpl
adb shell pm uninstall -k --user 0 pl.supermemo.asterix
adb shell pm uninstall -k --user 0 com.hrs.android
adb shell pm uninstall -k --user 0 pl.infover.ebooki
adb shell pm uninstall -k --user 0 com.endomondo.android
adb shell pm uninstall -k --user 0 com.evernote
adb shell pm uninstall -k --user 0 com.dropbox.android
adb shell pm uninstall -k --user 0 com.sec.android.app.translator
adb shell pm uninstall -k --user 0 com.accuweather.android
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.ap.hero.accuweather
adb shell pm uninstall -k --user 0 com.shazam.android
adb shell pm uninstall -k --user 0 com.tripadvisor.tripadvisor
adb shell pm uninstall -k --user 0 com.samsung.android.tripwidget
